

GET https://localhost:5001/api/widgets HTTP/1.1

###

GET https://localhost:5001/api/widgets/3 HTTP/1.1

###

POST https://localhost:5001/api/widgets HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "name": "test widget",
  "color": "blue",
  "quantity": 23
}

###

PUT https://localhost:5001/api/widgets/1 HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "id": 3,
  "name": "new yellow widget",
  "color": "yellow",
  "quantity": 5
}

###

DELETE https://localhost:5001/api/widgets/10 HTTP/1.1

